### ISSUE TITLE
disable "focus" on mobile devices

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#64]
the grey textcolor on a red background (if faved) is a bit "meh". 
Maybe let it white and change (lighten/darken) the crimson red of the suggestion if marked via keyboard arrows instead ...

**Comment by n4bb12** [comment]
I think you posted two different changes in one issue.

1. what the title says
2. change existing colors on desktop devices

**Comment by n4bb12** [comment]
Regarding the colors on desktop:

There are three different properties: hovered, focused and favorited.

So these are 8 possible combinations:
- none
- hovered
- focused
- favorited
- hovered + focused
- hovered + favorited
- focused + favorited
- hovered + focused + favorited

Each of these possibilities needs to be distinguishable with a different combination of `color` and `background-color`.

At the same time, the colors should be meaningful and intuitive. Currently, a favorited item always has red in it. A focused item always has gray and a hovered item always has black.

It's kind of hard to cover all these combinations while having perfectly contrasting colors.

That said, what color would you suggest?

Do you think it would be a good idea to add an additional theme color so that we have more colors we can use?

**Comment by AgentGhost** [comment]
how about the pink we used on active buttons

**Comment by n4bb12** [comment]
For which of the 8 cases would you like to use pink and do you want to use it for background or text color?

**Comment by n4bb12** [comment]
The same question goes for slate gray.

**Comment by AgentGhost** [comment]
Hovering swaps bg & font color.

- hovered + focused + favorited (black bg & pink font)
- hovered + focused (black bg & lightgrey font)
- hovered + favorited (crimson bg & white font)
- focused + favorited (pink bg & black font)
- hovered (black bg & white font)
- focused (lightgrey bg & black font)
- favorited (white bg & crimson font)
- none (white bg & black font)
(bg=background)

OR alternatively as above except:
- hovered + focused (slategrey bg & white font)
- focused (white bg & slategrey font)
